---
name: Build Dev Distrobox Image
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at Midnight

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Buildah Action
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: xmltv
          layers: true
          platforms: linux/amd64
          tags: latest v1 ${{ github.sha }}
          containerfiles: |
            ./ci/Containerfile

      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io/kevindurb
          username: ${{ github.actor }}
          password: ${{ github.token }}
